# Generated by Django 3.2.16 on 2024-07-30 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('confirmation_code', models.CharField(max_length=255, null=True)),
                ('reference_code', models.CharField(max_length=255, null=True)),
                ('transaction_payload', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'INVALID'), (1, 'COMPLETED'), (2, 'FAILED'), (3, 'REVERSED'), (4, 'PENDING')], null=True)),
                ('date_updated', models.DateTimeField(null=True)),
                ('order_tracking_id', models.CharField(max_length=255, null=True)),
                ('payment_account', models.CharField(max_length=255, null=True)),
                ('currency', models.CharField(max_length=255, null=True)),
                ('payment_method', models.CharField(max_length=255, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.courses')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
