# Generated by Django 3.2.16 on 2024-09-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20240828_0621'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='courses',
            field=models.ManyToManyField(related_name='customers', to='courses.Lesson'),
        ),
    ]
